CREATE TABLE Bookings(
Id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
StartDate DATE NOT NULL,
EndDate DATE NOT NULL,
TotalCost DECIMAL(6,2),
CarId INT NOT NULL FOREIGN KEY(CarId) REFERENCES Cars(Id),
CustomerId INT NOT NULL FOREIGN KEY(CustomerId) REFERENCES Customers(Id));