CREATE TABLE Cars (
Id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
Make VARCHAR(30) NOT NULL,
Model VARCHAR(30) NOT NULL,
ModelYear SMALLINT NOT NULL,
PricePerDay DECIMAL(6,2) NOT NULL,
IsAvailable BIT NOT NULL);